/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rodrigo.menu;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import rodrigo.Utils.BackgroundPanel;
import rodrigo.Utils.DatabaseManager;
import rodrigo.Utils.UIUtils;
import rodrigo.models.User;
import rodrigo.models.UserDAO;

/**
 *
 * @author myself
 */
public class AuthScreen extends javax.swing.JFrame {

    /**
     * Creates new form AuthFrame
     */
    public AuthScreen() throws SQLException {
        setTitle("Login • Barber Agendement");
        setSize(500, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setUndecorated(true);  // Remover borda da janela

        // Criar o painel de fundo com a imagem
        BackgroundPanel bgPanel = new BackgroundPanel("icons/background.jpg"); // Substitua pelo caminho correto
        setContentPane(bgPanel);  // Adiciona o painel de fundo ao JFrame
        bgPanel.setLayout(null);  // Usar layout nulo para posicionar componentes manualmente

        // Inicializar os componentes
        initComponents();
        DatabaseManager.initDB();

        // Aplicar estilos aos botões
        UIUtils.styleButton(jbtn_login);
        UIUtils.styleButton(jbtn_sair);
        UIUtils.styleHover(jbtn_login);
        UIUtils.styleButton(jbtn_register);
        UIUtils.styleHover(jbtn_register);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        jbtn_login = new javax.swing.JButton();
        lbl_password = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        jtxf_user = new javax.swing.JTextField();
        jpswd_password = new javax.swing.JPasswordField();
        jbtn_sair = new javax.swing.JButton();
        jbtn_register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(23, 27, 36));
        jPanel.setForeground(new java.awt.Color(153, 153, 153));

        lbl_titulo.setBackground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("✂ BARBER SCHEDULER");

        jbtn_login.setText("[ ENTRAR ]");
        jbtn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_loginActionPerformed(evt);
            }
        });

        lbl_password.setForeground(new java.awt.Color(212, 175, 55));
        lbl_password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_password.setText(" 🔒 PALAVRA-PASSE :");

        lbl_user.setBackground(new java.awt.Color(255, 255, 255));
        lbl_user.setForeground(new java.awt.Color(212, 175, 55));
        lbl_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_user.setText("👤 UTILIZADOR :");

        jtxf_user.setBackground(new java.awt.Color(255, 255, 255));
        jtxf_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxf_userActionPerformed(evt);
            }
        });

        jpswd_password.setBackground(new java.awt.Color(255, 255, 255));
        jpswd_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpswd_passwordActionPerformed(evt);
            }
        });

        jbtn_sair.setText("X");
        jbtn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_sairActionPerformed(evt);
            }
        });

        jbtn_register.setText("[ REGISTRAR ]");
        jbtn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_registerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(lbl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(lbl_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jbtn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbl_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jpswd_password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(jtxf_user, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(9, 9, 9))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxf_user, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_user, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_password, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpswd_password, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_sairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtn_sairActionPerformed

    private void jtxf_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxf_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxf_userActionPerformed

    private void jpswd_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpswd_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpswd_passwordActionPerformed

    private void jbtn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_registerActionPerformed
        String username = jtxf_user.getText().trim();
        String password = new String(jpswd_password.getPassword()).trim();

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        UserDAO userDAO = new UserDAO();
        if (userDAO.usernameExists(username)) {
            JOptionPane.showMessageDialog(this, "O nome de utilizador já existe.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        User newUser = new User("Nome do Utilizador", username, password, "email@example.com", "123456789");
        if (userDAO.registarUtilizador(newUser)) {
            JOptionPane.showMessageDialog(this, "Utilizador registado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            new ClientScreen().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao registar utilizador.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtn_registerActionPerformed

    private void jbtn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_loginActionPerformed
        // Pega o username e password inseridos pelo utilizador
        String username = jtxf_user.getText().trim();
        String password = new String(jpswd_password.getPassword()).trim();

        // Verifica se o login é válido e também devolve o tipo de utilizador
        String tipo = autenticarUsuario(username, password);

        if (tipo == null) {
            // Caso o login falhe, mostra uma mensagem de erro
            JOptionPane.showMessageDialog(this, "Username ou Password incorretos", "Erro de Login", JOptionPane.ERROR_MESSAGE);
        } else {
            // Se a autenticação for bem-sucedida, abre o menu correspondente ao tipo de utilizador
            if (tipo.equals("cliente")) {
                // Menu de Cliente
                JOptionPane.showMessageDialog(this, "Bem-vindo, Cliente!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();  // Fecha a tela de login
                new ClientScreen().setVisible(true);  // Abre o menu do cliente
            } else if (tipo.equals("barbeiro")) {
                // Menu de Barbeiro (admin)
                JOptionPane.showMessageDialog(this, "Bem-vindo, Barbeiro/Admin!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();  // Fecha a tela de login
                new BarberScreen().setVisible(true);  // Abre o menu do barbeiro
            }
        }
    }

    private String autenticarUsuario(String username, String password) {
        UserDAO userDAO = new UserDAO();
        return userDAO.autenticar(username, password); // Agora devolve o tipo ("cliente" ou "barbeiro")
    }//GEN-LAST:event_jbtn_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AuthScreen().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AuthScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_login;
    private javax.swing.JButton jbtn_register;
    private javax.swing.JButton jbtn_sair;
    private javax.swing.JPasswordField jpswd_password;
    private javax.swing.JTextField jtxf_user;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_user;
    // End of variables declaration//GEN-END:variables
}
