/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rodrigo.menu;

import javax.swing.JFrame;
import rodrigo.Utils.UIUtils;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import static rodrigo.Utils.Sessao.getClienteId;
import java.sql.PreparedStatement;

public class BookingScreen extends javax.swing.JFrame {

    /**
     * Creates new form BookingScreen
     */

    public BookingScreen() {
        setTitle("Agendamento • Barber Agendement");
        setSize(500, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setUndecorated(true);
        initComponents();
        UIUtils.styleButton(jbtn_voltar);
        UIUtils.styleButton(jbtn_confirm);
        preencherComboBoxes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_Tbooking = new javax.swing.JLabel();
        lbl_data = new javax.swing.JLabel();
        lbl_hora = new javax.swing.JLabel();
        lbl_barbeiro = new javax.swing.JLabel();
        lbl_servico = new javax.swing.JLabel();
        jbtn_voltar = new javax.swing.JButton();
        jbtn_confirm = new javax.swing.JButton();
        jtxt_data = new javax.swing.JTextField();
        jtxt_hora = new javax.swing.JTextField();
        jcb_barbeiro = new javax.swing.JComboBox<>();
        jcb_servico = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(23, 27, 36));

        lbl_titulo.setBackground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("✂ BARBER SCHEDULER");

        lbl_Tbooking.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Tbooking.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_Tbooking.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Tbooking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Tbooking.setText("AGENDAR SERVIÇO");

        lbl_data.setBackground(new java.awt.Color(255, 255, 255));
        lbl_data.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_data.setForeground(new java.awt.Color(255, 255, 255));
        lbl_data.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_data.setText("Data:");

        lbl_hora.setBackground(new java.awt.Color(255, 255, 255));
        lbl_hora.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_hora.setForeground(new java.awt.Color(255, 255, 255));
        lbl_hora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_hora.setText("Hora:");

        lbl_barbeiro.setBackground(new java.awt.Color(255, 255, 255));
        lbl_barbeiro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_barbeiro.setForeground(new java.awt.Color(255, 255, 255));
        lbl_barbeiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_barbeiro.setText("Barbeiro:");

        lbl_servico.setBackground(new java.awt.Color(255, 255, 255));
        lbl_servico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_servico.setForeground(new java.awt.Color(255, 255, 255));
        lbl_servico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_servico.setText("Serviço:");

        jbtn_voltar.setText("[ VOLTAR ]");
        jbtn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_voltarActionPerformed(evt);
            }
        });

        jbtn_confirm.setText("[ CONFIRMAR )");
        jbtn_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_confirmActionPerformed(evt);
            }
        });

        jtxt_data.setText("03/05/2025");

        jtxt_hora.setText("20:20");

        jcb_barbeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_barbeiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jbtn_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_confirm)
                .addGap(43, 43, 43))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_barbeiro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_hora, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_servico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_data, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxt_data)
                            .addComponent(jtxt_hora, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(jcb_barbeiro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcb_servico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lbl_Tbooking, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lbl_Tbooking, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_data, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_barbeiro)
                    .addComponent(jcb_barbeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_servico, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_servico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_voltar)
                    .addComponent(jbtn_confirm))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_voltarActionPerformed
        ClientScreen MenuScreen = new ClientScreen();
        MenuScreen.setVisible(true);
        this.dispose();  // Fecha a tela de login
    }//GEN-LAST:event_jbtn_voltarActionPerformed

    private void jbtn_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_confirmActionPerformed
        String data = jtxt_data.getText().trim();
        String hora = jtxt_hora.getText().trim();
        String barbeiro = (String) jcb_barbeiro.getSelectedItem();
        String servico = (String) jcb_servico.getSelectedItem();

        if (data.isEmpty() || hora.isEmpty() || barbeiro == null || servico == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Preenche todos os campos!", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Connection con = DriverManager.getConnection("jdbc:sqlite:barber.db");

            // ID do cliente autenticado (adapta isto à tua lógica de login)
            int clienteId = getClienteId(); // <-- Este método tem de devolver o ID do cliente atual

            // Verifica se já existe agendamento para o mesmo horário e barbeiro
            String checkSql = "SELECT * FROM Agendamentos WHERE data = ? AND hora = ? AND barbeiro = ?";
            PreparedStatement checkStmt = con.prepareStatement(checkSql);
            checkStmt.setString(1, data);
            checkStmt.setString(2, hora);
            checkStmt.setString(3, barbeiro);
            ResultSet rs = checkStmt.executeQuery();

            if (rs.next()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Esse horário já está ocupado!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            } else {
                // Insere o novo agendamento com cliente_id
                String insertSql = "INSERT INTO Agendamentos (data, hora, barbeiro, servico, cliente_id) VALUES (?, ?, ?, ?, ?)";
                PreparedStatement insertStmt = con.prepareStatement(insertSql);
                insertStmt.setString(1, data);
                insertStmt.setString(2, hora);
                insertStmt.setString(3, barbeiro);
                insertStmt.setString(4, servico);
                insertStmt.setInt(5, clienteId);
                insertStmt.executeUpdate();

                javax.swing.JOptionPane.showMessageDialog(this, "Agendamento confirmado!");
            }

            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao agendar. Tenta novamente.", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtn_confirmActionPerformed

    private void jcb_barbeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_barbeiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_barbeiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel;
    private javax.swing.JButton jbtn_confirm;
    private javax.swing.JButton jbtn_voltar;
    private javax.swing.JComboBox<String> jcb_barbeiro;
    private javax.swing.JComboBox<String> jcb_servico;
    private javax.swing.JTextField jtxt_data;
    private javax.swing.JTextField jtxt_hora;
    private javax.swing.JLabel lbl_Tbooking;
    private javax.swing.JLabel lbl_barbeiro;
    private javax.swing.JLabel lbl_data;
    private javax.swing.JLabel lbl_hora;
    private javax.swing.JLabel lbl_servico;
    private javax.swing.JLabel lbl_titulo;
    // End of variables declaration//GEN-END:variables

    private void preencherComboBoxes() {
// Preenche o ComboBox com os barbeiros
        try {
            Connection con = DriverManager.getConnection("jdbc:sqlite:barber.db");
            Statement stmt = con.createStatement();
// Altera a query para fazer JOIN entre Barbeiros e Utilizadores
            ResultSet rs = stmt.executeQuery(
                    "SELECT u.nome "
                    + "FROM Barbeiros b "
                    + "JOIN Utilizadores u ON b.utilizador_id = u.id"
            );

            while (rs.next()) {
                jcb_barbeiro.addItem(rs.getString("nome"));
            }
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }

// Preenche o ComboBox com os serviços
        try {
            Connection con = DriverManager.getConnection("jdbc:sqlite:barber.db");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT servico_nome FROM servicos");
            while (rs.next()) {
                jcb_servico.addItem(rs.getString("servico_nome"));
            }
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
