/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rodrigo.menu;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import rodrigo.Utils.UIUtils;

/**
 *
 * @author myself
 */
public class ClientScreen extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public ClientScreen() {
        setTitle("Menu • Barber Agendement");
        setSize(500, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setUndecorated(true);
        initComponents();
// aplicação dos temas
        UIUtils.styleButton(jbtn_servicos);
        UIUtils.styleButton(jbtn_Agendar);
        UIUtils.styleButton(jbtn_Reviews);
        UIUtils.styleButton(jbtn_Ajuda);
        UIUtils.styleButton(jbtn_voltar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtn_Agendar = new javax.swing.JButton();
        jbtn_servicos = new javax.swing.JButton();
        jbtn_Reviews = new javax.swing.JButton();
        jbtn_Ajuda = new javax.swing.JButton();
        jbtn_voltar = new javax.swing.JButton();
        lbl_titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(23, 27, 36));

        jbtn_Agendar.setText("✂ AGENDAR ✂");
        jbtn_Agendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_AgendarActionPerformed(evt);
            }
        });

        jbtn_servicos.setText("💈 SERVIÇOS 💈 ");
        jbtn_servicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_servicosActionPerformed(evt);
            }
        });

        jbtn_Reviews.setText("⭐ AVALIAÇÕES ⭐");
        jbtn_Reviews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ReviewsActionPerformed(evt);
            }
        });

        jbtn_Ajuda.setText("❓ AJUDA ❓");
        jbtn_Ajuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_AjudaActionPerformed(evt);
            }
        });

        jbtn_voltar.setText("[ VOLTAR ]");
        jbtn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_voltarActionPerformed(evt);
            }
        });

        lbl_titulo.setBackground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("✂ BARBER SCHEDULER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_servicos, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_Agendar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_Ajuda, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_Reviews, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jbtn_servicos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_Agendar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_Reviews, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_Ajuda, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jbtn_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_voltarActionPerformed
        // TODO add your handling code here:
        AuthScreen AuthScreen = null;
        try {
            AuthScreen = new AuthScreen();
        } catch (SQLException ex) {
            Logger.getLogger(ClientScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        AuthScreen.setVisible(true);
        this.dispose();  // Fecha a tela de login
    }//GEN-LAST:event_jbtn_voltarActionPerformed

    private void jbtn_servicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_servicosActionPerformed
        ServicesScreen ServicesScreen = new ServicesScreen();
        ServicesScreen.setVisible(true);
        this.dispose();  // Fecha a tela de login
    }//GEN-LAST:event_jbtn_servicosActionPerformed

    private void jbtn_AgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_AgendarActionPerformed
        BookingScreen BookingScreen = new BookingScreen();
        BookingScreen.setVisible(true);
        this.dispose();  // Fecha a tela de login
    }//GEN-LAST:event_jbtn_AgendarActionPerformed

    private void jbtn_ReviewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ReviewsActionPerformed
        ReviewsScreen ReviewsScreen = new ReviewsScreen();
        ReviewsScreen.setVisible(true);
        this.dispose();  // Fecha a tela de login
    }//GEN-LAST:event_jbtn_ReviewsActionPerformed

    private void jbtn_AjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_AjudaActionPerformed
        HelpScreen HelpScreen = new HelpScreen();
        HelpScreen.setVisible(true);
        this.dispose();  // Fecha a tela de login
    }//GEN-LAST:event_jbtn_AjudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_Agendar;
    private javax.swing.JButton jbtn_Ajuda;
    private javax.swing.JButton jbtn_Reviews;
    private javax.swing.JButton jbtn_servicos;
    private javax.swing.JButton jbtn_voltar;
    private javax.swing.JLabel lbl_titulo;
    // End of variables declaration//GEN-END:variables
}
